name: Build

on:
  push:
    branches: 
    - "main"
  pull_request:
    branches:
    - "main"
    - "feat/*"

jobs:
  build:
    name: "Build packages"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
    - name: Build
      run: dotnet build OpenApiSourceGenerator/OpenApiSourceGenerator.csproj --verbosity normal --configuration Release --output "./artifacts" -p:VersionPrefix="${GITVERSION_MAJORMINORPATCH}" -p:VersionSuffix="${GITVERSION_NUGETPRERELEASETAGV2}" -p:ContinuousIntegrationBuild=true
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: artifacts/*.nupkg

  publish:
    name: "Publish packages to nuget.org"
    runs-on: ubuntu-latest
    environment: 'nuget'
    if: github.ref == 'refs/heads/main'
    needs:
    - build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: packages
        path: artifacts
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Publish the package to nuget.org
      run: dotnet nuget push ./artifacts/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_KEY }}